In [15]:
import pandas as pd
import numpy as np
import os
import re

In [7]:


folder_path = '../dataset/Flood/'
dataframes = {}

for filename in os.listdir(folder_path):
    if filename.endswith('.xlsx'):
        file_path = os.path.join(folder_path, filename)

        df = pd.read_excel(file_path)

        key = os.path.splitext(filename)[0]
        dataframes[key] = df

        globals()[key] = df

# New York

In [9]:
NewYork_100.head(10)

,Date,"Temperature,water,deg C,(Maximum)ALBANY-NY","Temperature,water,deg C,(Minimum)ALBANY-NY","Temperature,water,deg C,(Mean)ALBANY-NY","Temperature,water,deg C,(Maximum)ALBANY-NY.1","Temperature,water,deg C,(Minimum)ALBANY-NY.1","Temperature,water,deg C,(Mean)ALBANY-NY.1","Specific conductance,wat unfuS/cm @25 degC,(Maximum)ALBANY-NY","Specific conductance,wat unfuS/cm @25 degC,(Minimum)ALBANY-NY","Specific conductance,wat unfuS/cm @25 degC,(Mean)ALBANY-NY",...,"Specif\nic \nconduc\ntance,\nwat unf\nuS/cm @\n25 degC,\n(Mean)SKANEATELES-NY","Temper\nature,\nwater,\ndeg C,\n(Maximum)PORT_HENRY-NY","Temper\nature,\nwater,\ndeg C,\n(Minimum)PORT_HENRY-NY","Temper\nature,\nwater,\ndeg C,\n(Mean)PORT_HENRY-NY","Precip\nitation\ntotal,\ninches,\n(Sum)PORT_HENRY-NY","Temper\nature,\nwater,\ndeg C,\n(Minimum)ROUSES_POINT-NY","Temper\nature,\nwater,\ndeg C,\n(Mean)ROUSES_POINT-NY","Temperature,water,deg C,(Maximum)ROUSES_POINT-NY","Daily Mean Discharge, cubic feet per second - DUNHAM_BASIN-NY","Daily Instantaneous Gage height, feet - CRANBERRY_LAKE-NY"
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-01,14.4P,13.4P,14.0P,14.0P,13.1P,13.7P,229P,206P,220P,...,294P,10.8P,9.5P,10.0P,0.00P,8.6P,8.9P,9.2P,71.2P,16.30A
2,2024-05-02,15.4P,14.4P,14.8P,14.8P,14.0P,14.4P,239P,211P,225P,...,293P,10.5P,9.8P,10.1P,0.00P,8.5P,9.0P,9.5P,68.1P,16.30A
3,2024-05-03,16.0P,15.4P,15.6P,16.0P,14.8P,15.5P,244P,209P,229P,...,292P,11.5P,9.7P,10.5P,0.00P,8.9P,9.5P,10.1P,67.4P,16.30A
4,2024-05-04,16.4P,15.5P,16.0P,16.3P,15.4P,15.7P,232P,177P,208P,...,293P,10.3P,9.7P,10.0P,0.00P,9.6P,10.3P,10.7P,66.3P,16.30A
5,2024-05-05,16.0P,15.0P,15.6P,15.9P,15.1P,15.5P,222P,200P,212P,...,294P,9.7P,9.2P,9.4P,0.23P,10.0P,10.2P,10.4P,72.6P,16.30A
6,2024-05-06,15.6P,14.8P,15.0P,15.2P,14.7P,14.9P,237P,211P,221P,...,294P,11.9P,9.2P,10.0P,0.08P,10.1P,10.7P,11.5P,71.6P,16.30A
7,2024-05-07,15.9P,15.2P,15.5P,15.6P,15.1P,15.2P,250P,225P,237P,...,293P,12.7P,9.9P,11.1P,0.00P,10.3P,11.0P,12.0P,67.9P,16.30A
8,2024-05-08,16.5P,15.7P,15.9P,16.0P,15.3P,15.6P,240P,202P,225P,...,293P,12.4P,10.6P,11.7P,0.03P,10.9P,11.1P,11.3P,75.8P,16.40A
9,2024-05-09,16.6P,16.1P,16.3P,16.2P,15.7P,16.0P,242P,210P,228P,...,294P,11.8P,10.6P,11.2P,0.00P,10.6P,11.3P,12.3P,68.4P,16.40A

In [11]:
print(NewYork_100.columns)

Index(['Date', 'Temperature,water,deg C,(Maximum)ALBANY-NY',
       'Temperature,water,deg C,(Minimum)ALBANY-NY',
       'Temperature,water,deg C,(Mean)ALBANY-NY',
       'Temperature,water,deg C,(Maximum)ALBANY-NY.1',
       'Temperature,water,deg C,(Minimum)ALBANY-NY.1',
       'Temperature,water,deg C,(Mean)ALBANY-NY.1',
       'Specific conductance,wat unfuS/cm @25 degC,(Maximum)ALBANY-NY',
       'Specific conductance,wat unfuS/cm @25 degC,(Minimum)ALBANY-NY',
       'Specific conductance,wat unfuS/cm @25 degC,(Mean)ALBANY-NY',
       'Discharge,ft3/s,(Mean)SCHOHARIE_RESERVOIR-NY',
       'Temperature,water,deg C,(Maximum)SCHOHARIE_RESERVOIR-NY',
       'Temperature,water,deg C,(Minimum)SCHOHARIE_RESERVOIR-NY',
       'Temperature,water,deg C,(Mean)SCHOHARIE_RESERVOIR-NY',
       'Temperature,water,deg C,[at1,224ftaboveNAVDof1988](Minimum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,263ftaboveNAVDof1988](Minimum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,224ftaboveNAVDof1988](Maximum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,187ftaboveNAVDof1988](Maximum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,263ftaboveNAVDof1988](Maximum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,224ftaboveNAVDof1988](Mean)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,263ftaboveNAVDof1988](Mean)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,187ftaboveNAVDof1988](Minimum)LEWBEACH-NY',
       'Temperature,water,deg C,[at1,187ftaboveNAVDof1988](Mean)LEWBEACH-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,053\nft\nabove\nNAVD\nof\n1988]\n(Minimum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,053\nft\nabove\nNAVD\nof\n1988]\n(Mean)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,107\nft\nabove\nNAVD\nof\n1988]\n(Mean)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,107\nft\nabove\nNAVD\nof\n1988]\n(Minimum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,144\nft\nabove\nNAVD\nof\n1988]\n(MeanKELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,107\nft\nabove\nNAVD\nof\n1988]\n(Maximum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,144\nft\nabove\nNAVD\nof\n1988]\n(Minimum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,144\nft\nabove\nNAVD\nof\n1988]\n(Maximum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,053\nft\nabove\nNAVD\nof\n1988]\n(Maximum)KELSEY-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,425\nft\nabove\nNAVD\nof\n1988]\n(Maximum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,425\nft\nabove\nNAVD\nof\n1988]\n(Mean)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,355\nft\nabove\nNAVD\nof\n1988]\n(Minimum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,355\nft\nabove\nNAVD\nof\n1988]\n(Mean)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,383\nft\nabove\nNAVD\nof\n1988]\n(Minimum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,383\nft\nabove\nNAVD\nof\n1988]\n(Maximum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,355\nft\nabove\nNAVD\nof\n1988]\n(Maximum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,383\nft\nabove\nNAVD\nof\n1988]\n(Mean)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n[at\n1,425\nft\nabove\nNAVD\nof\n1988]\n(Minimum)NEVERSINK-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Maximum)SKANEATELES-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Minimum)SKANEATELES-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Mean)SKANEATELES-NY',
       'Specif\nic \nconduc\ntance,\nwat unf\nuS/cm @\n25 degC,\n(Maximum)SKANEATELES-NY',
       'Specif\nic \nconduc\ntance,\nwat unf\nuS/cm @\n25 degC,\n(Minimum)SKANEATELES-NY',
       'Specif\nic \nconduc\ntance,\nwat unf\nuS/cm @\n25 degC,\n(Mean)SKANEATELES-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Maximum)PORT_HENRY-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Minimum)PORT_HENRY-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Mean)PORT_HENRY-NY',
       'Precip\nitation\ntotal,\ninches,\n(Sum)PORT_HENRY-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Minimum)ROUSES_POINT-NY',
       'Temper\nature,\nwater,\ndeg C,\n(Mean)ROUSES_POINT-NY',
       'Temperature,water,deg C,(Maximum)ROUSES_POINT-NY',
       'Daily Mean Discharge, cubic feet per second - DUNHAM_BASIN-NY',
       'Daily Instantaneous Gage height, feet - CRANBERRY_LAKE-NY'],
      dtype='object')

## Refer Data Dictionary

In [12]:
column_mapping = {
    'Date': 'Date',
    'Temperature,water,deg C,(Maximum)ALBANY-NY': 'A_MaxT_degC',
    'Temperature,water,deg C,(Minimum)ALBANY-NY': 'A_MinT_degC',
    'Temperature,water,deg C,(Mean)ALBANY-NY': 'A_MeanT_degC',
    'Temperature,water,deg C,(Maximum)ALBANY-NY.1': 'A_MaxT_degC',
    'Temperature,water,deg C,(Minimum)ALBANY-NY.1': 'A_MinT_degC',
    'Temperature,water,deg C,(Mean)ALBANY-NY.1': 'A_MeanT_degC',
    'Specific conductance,wat unfuS/cm @25 degC,(Maximum)ALBANY-NY': 'A_MaxSC_ft',
    'Specific conductance,wat unfuS/cm @25 degC,(Minimum)ALBANY-NY': 'A_MinSC_ft',
    'Specific conductance,wat unfuS/cm @25 degC,(Mean)ALBANY-NY': 'A_MeanSC_ft',
    'Specif\nic \nconduc\ntance,\nwat unf\nuS/cm @\n25 degC,\n(Mean)SKANEATELES-NY': 'B_MeanSC_ft',
    'Temper\nature,\nwater,\ndeg C,\n(Maximum)PORT_HENRY-NY': 'C_MaxT_degC',
    'Temper\nature,\nwater,\ndeg C,\n(Minimum)PORT_HENRY-NY': 'C_MinT_degC',
    'Temper\nature,\nwater,\ndeg C,\n(Mean)PORT_HENRY-NY': 'C_MeanT_degC',
    'Precip\nitation\ntotal,\ninches,\n(Sum)PORT_HENRY-NY': 'C_D-SP_in',
    'Temper\nature,\nwater,\ndeg C,\n(Minimum)ROUSES_POINT-NY': 'D_MinT_degC',
    'Temper\nature,\nwater,\ndeg C,\n(Mean)ROUSES_POINT-NY': 'D_MeanT_degC',
    'Temperature,water,deg C,(Maximum)ROUSES_POINT-NY': 'D_MaxT_degC',
    'Daily Mean Discharge, cubic feet per second - DUNHAM_BASIN-NY': 'E_D-MD_ft^3/s',
    'Daily Instantaneous Gage height, feet - CRANBERRY_LAKE-NY': 'F_D-IGH_ft'
}

NewYork_100.rename(columns=column_mapping, inplace=True)

In [13]:
NewYork_100.head(10)

,Date,A_MaxT_degC,A_MinT_degC,A_MeanT_degC,A_MaxT_degC,A_MinT_degC,A_MeanT_degC,A_MaxSC_ft,A_MinSC_ft,A_MeanSC_ft,...,B_MeanSC_ft,C_MaxT_degC,C_MinT_degC,C_MeanT_degC,C_D-SP_in,D_MinT_degC,D_MeanT_degC,D_MaxT_degC,E_D-MD_ft^3/s,F_D-IGH_ft
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-01,14.4P,13.4P,14.0P,14.0P,13.1P,13.7P,229P,206P,220P,...,294P,10.8P,9.5P,10.0P,0.00P,8.6P,8.9P,9.2P,71.2P,16.30A
2,2024-05-02,15.4P,14.4P,14.8P,14.8P,14.0P,14.4P,239P,211P,225P,...,293P,10.5P,9.8P,10.1P,0.00P,8.5P,9.0P,9.5P,68.1P,16.30A
3,2024-05-03,16.0P,15.4P,15.6P,16.0P,14.8P,15.5P,244P,209P,229P,...,292P,11.5P,9.7P,10.5P,0.00P,8.9P,9.5P,10.1P,67.4P,16.30A
4,2024-05-04,16.4P,15.5P,16.0P,16.3P,15.4P,15.7P,232P,177P,208P,...,293P,10.3P,9.7P,10.0P,0.00P,9.6P,10.3P,10.7P,66.3P,16.30A
5,2024-05-05,16.0P,15.0P,15.6P,15.9P,15.1P,15.5P,222P,200P,212P,...,294P,9.7P,9.2P,9.4P,0.23P,10.0P,10.2P,10.4P,72.6P,16.30A
6,2024-05-06,15.6P,14.8P,15.0P,15.2P,14.7P,14.9P,237P,211P,221P,...,294P,11.9P,9.2P,10.0P,0.08P,10.1P,10.7P,11.5P,71.6P,16.30A
7,2024-05-07,15.9P,15.2P,15.5P,15.6P,15.1P,15.2P,250P,225P,237P,...,293P,12.7P,9.9P,11.1P,0.00P,10.3P,11.0P,12.0P,67.9P,16.30A
8,2024-05-08,16.5P,15.7P,15.9P,16.0P,15.3P,15.6P,240P,202P,225P,...,293P,12.4P,10.6P,11.7P,0.03P,10.9P,11.1P,11.3P,75.8P,16.40A
9,2024-05-09,16.6P,16.1P,16.3P,16.2P,15.7P,16.0P,242P,210P,228P,...,294P,11.8P,10.6P,11.2P,0.00P,10.6P,11.3P,12.3P,68.4P,16.40A

In [16]:
def remove_alpha(cell):
    if isinstance(cell, str):
        return re.sub(r'[A-Za-z]', '', cell)
    return cell

In [23]:
NewYork_100 = NewYork_100.applymap(remove_alpha)
NewYork_100 = NewYork_100.drop(0).reset_index(drop=True)

NewYork_100.head()

,Date,A_MaxT_degC,A_MinT_degC,A_MeanT_degC,A_MaxT_degC,A_MinT_degC,A_MeanT_degC,A_MaxSC_ft,A_MinSC_ft,A_MeanSC_ft,...,B_MeanSC_ft,C_MaxT_degC,C_MinT_degC,C_MeanT_degC,C_D-SP_in,D_MinT_degC,D_MeanT_degC,D_MaxT_degC,E_D-MD_ft^3/s,F_D-IGH_ft
0,2024-05-01,14.4,13.4,14.0,14.0,13.1,13.7,229,206,220,...,294,10.8,9.5,10.0,0.00,8.6,8.9,9.2,71.2,16.30
1,2024-05-02,15.4,14.4,14.8,14.8,14.0,14.4,239,211,225,...,293,10.5,9.8,10.1,0.00,8.5,9.0,9.5,68.1,16.30
2,2024-05-03,16.0,15.4,15.6,16.0,14.8,15.5,244,209,229,...,292,11.5,9.7,10.5,0.00,8.9,9.5,10.1,67.4,16.30
3,2024-05-04,16.4,15.5,16.0,16.3,15.4,15.7,232,177,208,...,293,10.3,9.7,10.0,0.00,9.6,10.3,10.7,66.3,16.30
4,2024-05-05,16.0,15.0,15.6,15.9,15.1,15.5,222,200,212,...,294,9.7,9.2,9.4,0.23,10.0,10.2,10.4,72.6,16.30

In [24]:
nan_locations = NewYork_100.isna()
print(nan_locations)

     Date  A_MaxT_degC  A_MinT_degC  A_MeanT_degC  A_MaxT_degC  A_MinT_degC  \
0   False        False        False         False        False        False
1   False        False        False         False        False        False
2   False        False        False         False        False        False
3   False        False        False         False        False        False
4   False        False        False         False        False        False
..    ...          ...          ...           ...          ...          ...
95  False        False        False         False        False        False
96  False        False        False         False        False        False
97  False        False        False         False        False        False
98  False        False        False         False        False        False
99  False        False        False         False        False        False

    A_MeanT_degC  A_MaxSC_ft  A_MinSC_ft  A_MeanSC_ft  ...  B_MeanSC_ft  \
0          False       False       False        False  ...        False
1          False       False       False        False  ...        False
2          False       False       False        False  ...        False
3          False       False       False        False  ...        False
4          False       False       False        False  ...        False
..           ...         ...         ...          ...  ...          ...
95         False       False       False        False  ...        False
96         False       False       False        False  ...        False
97         False       False       False        False  ...        False
98         False       False       False        False  ...        False
99         False       False       False        False  ...        False

    C_MaxT_degC  C_MinT_degC  C_MeanT_degC  C_D-SP_in  D_MinT_degC  \
0         False        False         False      False        False
1         False        False         False      False        False
2         False        False         False      False        False
3         False        False         False      False        False
4         False        False         False      False        False
..          ...          ...           ...        ...          ...
95        False        False         False      False        False
96        False        False         False      False        False
97        False        False         False      False        False
98        False        False         False      False        False
99        False        False         False      False        False

    D_MeanT_degC  D_MaxT_degC  E_D-MD_ft^3/s  F_D-IGH_ft
0          False        False          False       False
1          False        False          False       False
2          False        False          False       False
3          False        False          False       False
4          False        False          False       False
..           ...          ...            ...         ...
95         False        False          False        True
96         False        False          False        True
97         False        False          False        True
98         False        False          False        True
99         False        False          False        True

[100 rows x 56 columns]